### ISSUE TITLE
Error with CarEnhancer

### ISSUE THREAD

**Issue by morg1807** [VynDragon/GTA-Stuffs#1]
https://gyazo.com/37f57f44cd99acf46ef4d2e6c2bd59ad
CarEnhancer.ini crashes during loading, is it due to my scripthook version?

**Comment by VynDragon** [comment]
maybe, are you using 0.393.4a ?

**Comment by VynDragon** [comment]
Ok, i think i fixed it.
Fixed version will be uploaded shortly, tell me if the issue is fixed.
